/**
 * Utility functions for downloading files and archives in Apives Architect
 */

export function downloadFile(content: string, filename: string, type = 'text/plain') {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function downloadJsonFile(filename: string, data: any) {
  const content = typeof data === 'string' ? data : JSON.stringify(data, null, 2);
  downloadFile(content, filename.endsWith('.json') ? filename : `${filename}.json`, 'application/json');
}

export function downloadYamlFile(filename: string, content: string) {
  downloadFile(content, filename.endsWith('.yaml') || filename.endsWith('.yml') ? filename : `${filename}.yaml`, 'text/yaml');
}

export function exportPostmanCollection(project: any) {
  const nameSlug = project.name.toLowerCase().replace(/[^a-z0-9]/g, '_');
  const postmanCollection = {
    info: {
      name: `${project.name} API Collection`,
      description: project.description || 'Generated by Apives Architect IDE',
      schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: (project.endpoints || []).map((ep: any) => ({
      name: `${ep.method} ${ep.path}`,
      request: {
        method: ep.method,
        header: Object.entries(ep.headers || {}).map(([key, value]) => ({
          key,
          value: String(value),
          type: 'text'
        })),
        url: {
          raw: `{{baseUrl}}${ep.path}`,
          host: ['{{baseUrl}}'],
          path: ep.path.split('/').filter(Boolean)
        },
        description: ep.description
      },
      response: []
    })),
    variable: [
      {
        key: 'baseUrl',
        value: 'http://localhost:3000/api/v1',
        type: 'string'
      }
    ]
  };

  downloadJsonFile(`${nameSlug}_postman_collection.json`, postmanCollection);
}

/**
 * Downloads all files as an uncompressed plain-text bundle or multiple files trigger.
 */
export function downloadBackendPackage(projectName: string, framework: string, files: Array<{ name: string; path: string; content: string }>) {
  const nameSlug = projectName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  let bundleContent = `# ${projectName} - ${framework} Project Archive\n`;
  bundleContent += `# Generated by Apives Architect Engine\n`;
  bundleContent += `# Date: ${new Date().toISOString()}\n\n`;

  files.forEach(file => {
    bundleContent += `=========================================\n`;
    bundleContent += `FILE: ${file.path} (${file.name})\n`;
    bundleContent += `=========================================\n\n`;
    bundleContent += file.content + `\n\n`;
  });

  downloadFile(bundleContent, `${nameSlug}-${framework.toLowerCase().replace(/[^a-z0-9]/g, '')}-project.txt`, 'text/plain');
}
